export const recipes = {
    "Agua+Fuego": "Vapor",
    "Fuego+Agua": "Vapor",
    "Agua+Tierra": "Barro",
    "Tierra+Agua": "Barro",
    "Fuego+Tierra": "Lava",
    "Tierra+Fuego": "Lava",
    "Viento+Tierra": "Polvo",
    "Tierra+Viento": "Polvo",
    "Viento+Fuego": "Humo",
    "Fuego+Viento": "Humo",
    "Vapor+Viento": "Nube",
    "Viento+Vapor": "Nube",
    "Nube+Tierra": "Niebla",
    "Tierra+Nube": "Niebla",
    "Agua+Agua": "Lago",
    "Fuego+Fuego": "Volcán",
    "Tierra+Tierra": "Montaña",
    "Viento+Viento": "Tornado",
    "Lago+Agua": "Océano",
    "Océano+Agua": "Mar",
    "Tierra+Océano": "Isla",
    "Isla+Árbol": "Palmera",
    "Barro+Fuego": "Ladrillo",
    "Ladrillo+Ladrillo": "Muro",
    "Muro+Muro": "Casa",
    "Casa+Casa": "Pueblo",
    "Pueblo+Pueblo": "Ciudad",
    "Tierra+Vida": "Humano",
    "Humano+Casa": "Familia",
    "Vapor+Tierra": "Géiser",
    "Humo+Niebla": "Smog",
    "Polvo+Fuego": "Pólvora",
    "Montaña+Agua": "Cascada",
    "Cascada+Agua": "Río",
    "Volcán+Agua": "Obsidiana",
    "Agua+Viento": "Ola",
    "Ola+Tierra": "Arena",
    "Arena+Fuego": "Vidrio",
    "Vidrio+Arena": "Reloj de arena",
    "Planta+Agua": "Pantano",
    "Planta+Tierra": "Árbol",
    "Árbol+Árbol": "Bosque",
    "Bosque+Vida": "Salvaje",
    "Vida+Polvo": "Alien",
    "Planta+Sol": "Flor",
    "Volcán+Montaña": "Cordillera",
    "Arena+Arena": "Desierto",
    "Desierto+Agua": "Oasis",
    "Nube+Agua": "Lluvia",
    "Lluvia+Lluvia": "Inundación",
    "Lluvia+Sol": "Arcoíris",
    "Fuego+Vapor": "Motor",
    "Motor+Carbón": "Tren",
    "Motor+Agua": "Barco de vapor",
    "Viento+Energía": "Tormenta",
    "Tormenta+Agua": "Trueno",
    "Vida+Agua": "Pez",
    "Vida+Tierra": "Animal",
    "Animal+Casa": "Mascota",

    // New additions for levels 1-15 path
    "Lluvia+Tierra": "Planta",
    "Tierra+Lluvia": "Planta",
    "Nube+Nube": "Tormenta",
    "Tormenta+Tierra": "Energía",
    "Tierra+Tormenta": "Energía",
    "Pantano+Energía": "Vida",
    "Energía+Pantano": "Vida"
};

export const emojiMap = {
    "Agua": "💧",
    "Fuego": "🔥",
    "Tierra": "🌍",
    "Viento": "💨",
    "Vapor": "💨",
    "Barro": "💩",
    "Lava": "🌋",
    "Polvo": "🌫️",
    "Humo": "🚬",
    "Lago": "🌊",
    "Volcán": "🌋",
    "Montaña": "🏔️",
    "Tornado": "🌪️",
    "Océano": "🌊",
    "Mar": "🌊",
    "Isla": "🏝️",
    "Ladrillo": "🧱",
    "Muro": "🧱",
    "Casa": "🏠",
    "Pueblo": "🏘️",
    "Ciudad": "🏙️",
    "Humano": "🧑",
    "Familia": "👨‍👩‍👧",
    "Géiser": "⛲",
    "Smog": "🌫️",
    "Pólvora": "🧨",
    "Cascada": "🌊",
    "Río": "🏞️",
    "Obsidiana": "⬛",
    "Ola": "🌊",
    "Arena": "🏖️",
    "Vidrio": "🥃",
    "Reloj de arena": "⏳",
    "Pantano": "🐊",
    "Árbol": "🌳",
    "Bosque": "🌲",
    "Salvaje": "🦁",
    "Alien": "👽",
    "Flor": "🌸",
    "Escritorio": "🖥️",
    "Palmera": "🌴",
    "Desierto": "🌵",
    "Oasis": "🏝️",
    "Lluvia": "🌧️",
    "Inundación": "🌊",
    "Arcoíris": "🌈",
    "Motor": "⚙️",
    "Tren": "🚂",
    "Barco de vapor": "🚢",
    "Tormenta": "⛈️",
    "Trueno": "⚡",
    "Pez": "🐟",
    "Animal": "🐶",
    "Mascota": "🐕",
    "Vida": "🧬",
    "Sol": "☀️",
    "Nube": "☁️",
    "Energía": "⚡",
    "Carbón": "🪨",
    "Niebla": "🌫️",
    "Planta": "🌱"
};

export const startingElements = ["Agua", "Fuego", "Tierra", "Viento"];
